apiVersion: charts.wanja.org/v1alpha1
kind: QuarkusSimple
metadata:
  name: quarkussimple-sample
spec:
  # Default values copied from <project_dir>/helm-charts/quarkus-simple/values.yaml
  config:
    greeting: This needs to be changed per stage!
  deployment:
    image: quay.io/rafaeltuelho/simple-quarkus
    includeHealthChecks: true
    replicas: 1
    version: "1.2.0"
  route:
    host: article-operator.apps-crc.testing
  
  
